from fastapi import APIRouter
from fastapi.responses import HTMLResponse
from app.signals.paper_tracker import paper_signal_tracker

router = APIRouter(tags=["paper-tracker"])

@router.get("/paper-tracker/data")
def data():
    try:
        return {"metrics": paper_signal_tracker.metrics(), "rows": paper_signal_tracker.rows(), "research_only": True, "trading": "DISABLED"}
    except Exception as exc:
        return {"metrics": {}, "rows": [], "error": str(exc), "research_only": True, "trading": "DISABLED"}

@router.get("/paper-tracker", response_class=HTMLResponse, include_in_schema=False)
def page() -> str:
    return HTML

HTML = r'''<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Paper P&L Tracker</title>
<style>
:root{font-family:Inter,system-ui,-apple-system,sans-serif;background:#080d19;color:#e8edf7;--p:#121a2c;--b:#26334d;--m:#8e9ab0;--g:#42d392;--r:#ff6f7d;--a:#f4c95d}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,#17243d,#080d19 45%);min-height:100vh}.wrap{max-width:1650px;margin:auto;padding:25px}.top{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;margin-bottom:16px}.title{font-size:29px;font-weight:800}.sub{color:var(--m);font-size:12px;margin-top:5px}.nav{display:flex;gap:8px;margin-top:12px;flex-wrap:wrap}.nav a{color:#b9c7df;text-decoration:none;border:1px solid var(--b);padding:7px 11px;border-radius:8px;background:#10182a;font-size:12px}.nav a.active{color:#fff;border-color:#52678f}.badge{border:1px solid var(--b);border-radius:999px;padding:9px 13px;background:#10182a}.panel{background:rgba(18,26,44,.96);border:1px solid var(--b);border-radius:14px;overflow:hidden;margin-bottom:15px}.stats{display:grid;grid-template-columns:repeat(7,1fr);gap:10px;padding:14px}.card{background:#0e1627;border:1px solid #22304a;border-radius:10px;padding:13px}.label{color:var(--m);font-size:11px;text-transform:uppercase;letter-spacing:.08em}.value{font-size:21px;font-weight:800;margin-top:5px}.table{overflow:auto}table{width:100%;border-collapse:collapse;min-width:1500px}th,td{padding:10px 12px;text-align:left;border-bottom:1px solid #202a40;font-size:12px;white-space:nowrap}th{color:var(--m);background:#0f1728}.profit,.target{color:var(--g)}.loss,.stop{color:var(--r)}.open{color:var(--a)}.empty{padding:45px;text-align:center;color:var(--m)}.note{padding:13px 18px;color:#b7c2d5;font-size:12px;border-top:1px solid var(--b)}@media(max-width:1000px){.stats{grid-template-columns:repeat(3,1fr)}}@media(max-width:600px){.stats{grid-template-columns:repeat(2,1fr)}.wrap{padding:13px}}
</style></head><body><div class="wrap">
<div class="top"><div><div class="title">Paper P&L Tracker</div><div class="sub">Every generated option signal tracked from first observed premium • no broker execution</div><div class="nav"><a href="/dashboard">Dashboard</a><a href="/strategy">SLO Strategy</a><a href="/dashboard/history">SLO History</a><a href="/paper-tracker" class="active">Paper P&L Tracker</a><a href="/reversal">Reversal</a><a href="/reversal/history">Reversal History</a></div></div><div id="clock" class="badge">—</div></div>
<div class="panel"><div class="stats">
<div class="card"><div class="label">Signals</div><div id="signals" class="value">—</div></div><div class="card"><div class="label">Profit</div><div id="profit" class="value profit">—</div></div><div class="card"><div class="label">Loss</div><div id="loss" class="value loss">—</div></div><div class="card"><div class="label">Open</div><div id="open" class="value open">—</div></div><div class="card"><div class="label">Target Hit</div><div id="target" class="value target">—</div></div><div class="card"><div class="label">Stop Hit</div><div id="stop" class="value stop">—</div></div><div class="card"><div class="label">Mark P&L</div><div id="pnl" class="value">—</div></div>
</div></div>
<div class="panel"><div class="table"><table><thead><tr><th>Generated (IST)</th><th>Entry (IST)</th><th>Exit (IST)</th><th>Last Observed (IST)</th><th>Underlying</th><th>Option</th><th>Direction</th><th>Signal</th><th>Score</th><th>Entry Premium</th><th>Current Premium</th><th>Stop</th><th>Target</th><th>Qty</th><th>P&L ₹</th><th>P&L %</th><th>Status</th><th>Reason</th></tr></thead><tbody id="rows"></tbody></table></div><div class="note">P&L is theoretical: (exit/current option premium − entry premium) × quantity. The tracker uses subsequent 5-minute option candles to determine whether target or stop was reached; if neither is reached, it shows OPEN_PROFIT/OPEN_LOSS during the session and finalizes at the last 5-minute close after 15:40 IST. This tracker never places an order.</div></div>
<script>
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const n=(v,d=2)=>v==null||v===''?'—':Number(v).toFixed(d);const ist=v=>{if(!v)return'—';try{return new Date(v).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false})}catch(e){return esc(v)}};async function refresh(){try{const r=await fetch('/paper-tracker/data');const d=await r.json();const m=d.metrics||{};signals.textContent=m.signals??0;profit.textContent=m.profit??0;loss.textContent=m.loss??0;open.textContent=m.open??0;target.textContent=m.target_hit??0;stop.textContent=m.stop_hit??0;pnl.textContent='₹ '+n(m.mark_to_market_pnl,2);clock.textContent=new Date().toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour12:false})+' IST';const rows=d.rows||[];document.getElementById('rows').innerHTML=rows.length?rows.map(x=>{const s=x.status||'OPEN';const cls=s==='PROFIT'||s==='TARGET_HIT'?'profit':s==='LOSS'||s==='STOP_HIT'?'loss':'open';return '<tr><td>'+ist(x.generated_at)+'</td><td>'+ist(x.entry_at)+'</td><td>'+ist(x.exit_at)+'</td><td>'+ist(x.last_observed_at)+'</td><td><b>'+esc(x.underlying)+'</b></td><td>'+esc(x.symbol)+' '+esc(x.option_type)+' '+esc(x.strike)+'</td><td>'+esc(x.direction)+'</td><td>'+esc(x.signal)+'</td><td>'+n(x.score)+'</td><td>'+n(x.entry_price,4)+'</td><td>'+n(x.current_price,4)+'</td><td>'+n(x.stop_price,4)+'</td><td>'+n(x.target_price,4)+'</td><td>'+esc(x.quantity)+'</td><td class="'+cls+'">'+n(x.mark_pnl,2)+'</td><td class="'+cls+'">'+n(x.pnl_pct,2)+'%</td><td class="'+cls+'"><b>'+esc(s)+'</b></td><td>'+esc(x.outcome_reason)+'</td></tr>'}).join(''):'<tr><td colspan="18" class="empty">No generated option signals have been tracked yet.</td></tr>'}catch(e){document.getElementById('rows').innerHTML='<tr><td colspan="16" class="empty">Tracker unavailable: '+esc(e.message)+'</td></tr>'}}refresh();setInterval(refresh,10000);
</script></div></body></html>'''
