from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(tags=["strategy-dashboard"])

HTML = r'''<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SLO Options Research</title>
<style>
:root{font-family:Inter,system-ui,-apple-system,sans-serif;background:#0b1020;color:#e8ecf5}*{box-sizing:border-box}body{margin:0;background:linear-gradient(180deg,#0b1020,#11182b);min-height:100vh}.wrap{max-width:1550px;margin:auto;padding:28px}.top{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:18px}.title{font-size:28px;font-weight:750}.sub{color:#8d98ad;margin-top:5px}.nav{display:flex;gap:8px;margin-bottom:18px}.nav a,.btn{color:#b9c2d4;text-decoration:none;border:1px solid #293650;background:#141c30;border-radius:9px;padding:8px 12px;font-size:13px}.nav a.active{color:#fff;border-color:#52678f}.status{padding:8px 13px;border:1px solid #26324a;border-radius:999px;font-size:13px}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:14px;margin-bottom:14px}.card,.panel{background:#141c30;border:1px solid #25314a;border-radius:14px}.card{padding:16px}.label{color:#8d98ad;font-size:12px;text-transform:uppercase;letter-spacing:.08em}.value{font-size:25px;font-weight:700;margin-top:8px}.panel{overflow:hidden;margin-bottom:16px}.panelhead{padding:17px 20px;border-bottom:1px solid #25314a;display:flex;justify-content:space-between;align-items:center;gap:12px}.muted{color:#8d98ad}.notice{padding:12px 14px;margin-bottom:14px;border:1px solid #3a3040;border-radius:10px;background:#181b2c;color:#b9c2d4;font-size:13px}.controls{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.controls input{width:90px;background:#0f1628;color:#e8ecf5;border:1px solid #2a3854;border-radius:8px;padding:8px}.tablewrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:1450px}th,td{text-align:left;padding:12px 14px;border-bottom:1px solid #202a40;font-size:13px;white-space:nowrap}th{color:#8d98ad;font-weight:600;background:#11182a}.bull{color:#42d392}.bear{color:#ff6f7d}.score{font-weight:750}.pill{padding:4px 8px;border-radius:6px;background:#202b43}.best{background:#19283a}.empty{padding:45px;text-align:center;color:#8d98ad}.two{display:grid;grid-template-columns:1fr 1fr;gap:14px}.detail{padding:20px}.detail h3{margin:0 0 14px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.metric{padding:12px;background:#10172a;border-radius:10px}.metric span{display:block;color:#8d98ad;font-size:11px}.metric b{display:block;margin-top:5px;font-size:15px}@media(max-width:1100px){.grid{grid-template-columns:repeat(3,1fr)}.two{grid-template-columns:1fr}}@media(max-width:700px){.grid{grid-template-columns:repeat(2,1fr)}.wrap{padding:16px}}
</style></head><body><div class="wrap">
<div class="top"><div><div class="title">SLO Options Research</div><div class="sub">Long-options candidate analysis • Research only • Trading disabled</div></div><div id="status" class="status">Connecting…</div></div>
<div class="nav"><a href="/dashboard">Flow Dashboard</a><a href="/strategy" class="active">SLO Strategy</a></div>
<div id="notice" class="notice">Waiting for the live scanner to warm up…</div>
<div class="grid"><div class="card"><div class="label">Candidates</div><div id="count" class="value">—</div></div><div class="card"><div class="label">Best Score</div><div id="best" class="value">—</div></div><div class="card"><div class="label">Bullish</div><div id="bull" class="value">—</div></div><div class="card"><div class="label">Bearish</div><div id="bear" class="value">—</div></div><div class="card"><div class="label">Feed Events</div><div id="events" class="value">—</div></div></div>
<div class="panel"><div class="panelhead"><strong>Top SLO Candidates</strong><div class="controls"><span class="muted">Minimum score</span><input id="minScore" type="number" min="0" max="100" value="65"><button class="btn" onclick="refresh()">Refresh</button><span class="muted" id="updated">—</span></div></div><div class="tablewrap"><table><thead><tr><th>#</th><th>Underlying</th><th>Direction</th><th>SLO Score</th><th>Signal</th><th>Option</th><th>Strike</th><th>Expiry</th><th>DTE</th><th>Premium</th><th>Stop</th><th>Target</th><th>Breakeven</th><th>Delta</th><th>Theta</th><th>IV</th><th>Volume</th><th>OI</th><th>Liquidity</th></tr></thead><tbody id="rows"><tr><td colspan="19" class="empty">Loading…</td></tr></tbody></table></div></div>
<div class="two"><div class="panel"><div class="panelhead"><strong>How the score is built</strong><span class="muted">SLO Options V1</span></div><div class="detail"><div class="metrics"><div class="metric"><span>Direction</span><b>45%</b></div><div class="metric"><span>Liquidity</span><b>20%</b></div><div class="metric"><span>Theta</span><b>20%</b></div><div class="metric"><span>Volatility</span><b>15%</b></div></div><p class="muted">The live adapter applies the SLO candidate-ranking formula to option-agent feed/depth and targeted option-chain enrichment. Direction comes from the live option-flow activity ranking.</p></div></div><div class="panel"><div class="panelhead"><strong>Selected research signal</strong><span class="muted">Highest-ranked candidate</span></div><div id="selected" class="detail"><div class="empty">No qualifying candidate yet.</div></div></div></div>
</div><script>
const api=location.origin;function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function num(v,d=2){return v==null?'—':Number(v).toFixed(d)}
async function refresh(){try{const min=Number(document.getElementById('minScore').value||65);const r=await fetch(api+'/strategy/results?limit=50&min_score='+encodeURIComponent(min));if(!r.ok)throw Error('API '+r.status);const d=await r.json();const a=d.results||[];document.getElementById('count').textContent=a.length;document.getElementById('best').textContent=a.length?num(a[0].total_score):'—';document.getElementById('bull').textContent=a.filter(x=>x.direction==='BULLISH').length;document.getElementById('bear').textContent=a.filter(x=>x.direction==='BEARISH').length;document.getElementById('events').textContent=d.scanner?.feed_events??'—';document.getElementById('status').textContent=d.scanner?.ranking_ready?'● Live ranking ready':'○ Warming up';document.getElementById('updated').textContent=d.scanner?.last_scan_timestamp?new Date(d.scanner.last_scan_timestamp).toLocaleTimeString():'—';document.getElementById('notice').textContent=d.research_only?'Research-only SLO analysis. No orders are placed. Candidates require live feed history plus liquidity/option-chain enrichment.':'Research service unavailable.';const body=document.getElementById('rows');if(!a.length){body.innerHTML='<tr><td colspan="19" class="empty">No candidate currently clears the selected score, DTE, liquidity and direction filters.</td></tr>';document.getElementById('selected').innerHTML='<div class="empty">No qualifying candidate yet.</div>';return}body.innerHTML=a.map((x,i)=>{const c=x.direction==='BULLISH'?'bull':'bear';return `<tr class="${i===0?'best':''}"><td>${i+1}</td><td><strong>${esc(x.underlying)}</strong></td><td class="${c}">${esc(x.direction)} ${num(x.direction_score,0)}</td><td class="score">${num(x.total_score)}</td><td class="${c}">${esc(x.signal)}</td><td>${esc(x.symbol)}</td><td>${num(x.strike,0)}</td><td>${esc(x.expiry)}</td><td>${esc(x.dte)}</td><td>${num(x.premium,2)}</td><td>${num(x.stop_premium,2)}</td><td>${num(x.target_premium,2)}</td><td>${num(x.breakeven,2)}</td><td>${num(x.delta,3)}</td><td>${num(x.theta,3)}</td><td>${x.iv==null?'—':num(Number(x.iv)*100,1)+'%'}</td><td>${esc(x.volume)}</td><td>${esc(x.open_interest)}</td><td>${num(x.liquidity_score)}</td></tr>`}).join('');const x=a[0];document.getElementById('selected').innerHTML=`<h3 class="${x.direction==='BULLISH'?'bull':'bear'}">${esc(x.signal)} · ${esc(x.underlying)}</h3><div class="metrics"><div class="metric"><span>Option</span><b>${esc(x.symbol)}</b></div><div class="metric"><span>SLO Score</span><b>${num(x.total_score)}</b></div><div class="metric"><span>Entry Premium</span><b>₹${num(x.premium,2)}</b></div><div class="metric"><span>Stop / Target</span><b>₹${num(x.stop_premium,2)} / ₹${num(x.target_premium,2)}</b></div></div><p class="muted">${esc(x.reason)}</p>`}catch(e){document.getElementById('status').textContent='API unavailable';document.getElementById('notice').textContent='Unable to load SLO strategy results: '+e.message}}
refresh();setInterval(refresh,10000);
</script></body></html>'''


@router.get("/strategy", response_class=HTMLResponse, include_in_schema=False)
def strategy_dashboard() -> str:
    return HTML
